### ISSUE TITLE
Request for Update

### ISSUE THREAD

**Issue by jayzan** [NuixSDK/Communication-Scanner#4]
Hello Jason! Would it be possible to get this updated? I am using 8.6 and tags don't get created after the search completes. Thank you!

**Comment by JuicyDragon** [comment]
Hello @jayzan we may need to dive deeper into the issue you are seeing.  I ran a few tests with the latest version of the script in Nuix 8.6.5.539 and the tags look to be getting applied appropriately in my tests.

Are you getting any errors?  Please detail the specific settings you are using so I can attempt recreate the issue.  Thanks 😄
